### ISSUE TITLE
Hitbox for previous/next client is not good.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Web-Site#1]
![screenshot from 2016-09-14 12-41-41](https://cloud.githubusercontent.com/assets/1911594/18509398/aa8af27a-7a78-11e6-9797-7ae0d385aebf.png)
As you can see hitbox is actually angled. Most people will go for the tip of the arrow and expect that to be hitbox. Link itself should be without rotation and properly positioned while `:before` or similar element should be rotated and positioned properly inside of the link.

**Comment by talrez11** [comment]
Fixed issue
